on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/test-flutter
    
    - name: cashrich
      uses: sandeshpatil21/cashrich
      with:
        server: ftp.cashrichapp.com
        username: sandesh@cashrichapp.com
        password: ${{ secrets.ftp_password }}
